services:
  web-dev:
    build:
      context: ./django-app/
    volumes:
      - ./django-app:/usr/src/app
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env/dev.env
    environment:
      - DJANGO_ENV=development
